<<<<<<< HEAD
name: Deploy to Hostinger
=======
name: Deploy Website
>>>>>>> 360037d71083d8cc38082d5963a52dd7e11b692a

on:
  push:
    branches:
      - main

jobs:
<<<<<<< HEAD
  ftp-deploy:
=======
  deploy:
>>>>>>> 360037d71083d8cc38082d5963a52dd7e11b692a
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

<<<<<<< HEAD
      - name: Upload files to Hostinger
=======
      - name: FTP Deploy
>>>>>>> 360037d71083d8cc38082d5963a52dd7e11b692a
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
<<<<<<< HEAD
          server-dir: /public_html/
=======
          server-dir: public_html/public/mspcbdesign/
>>>>>>> 360037d71083d8cc38082d5963a52dd7e11b692a
